stages:
  - test
  - build
  - deploy

test:
  image: cypress/browsers:node16.17.1-chrome105-ff104-edge
  stage: test
  before_script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm start & npx wait-on http://localhost:3000
  script:
    # run Cypress tests
    - npm run test:qa

build:
  # rules: 
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  image: node:latest    
  stage: build
  # variables:
  #   PUBLIC_URL: https://k2804.gtilab.io/final-project-2
  script:
    - yarn install      
    - yarn build
  artifacts:
    paths:
      - build/

pages:
  # rules: 
  #   - if: '$CI_MERGE_REQUEST_APPROVED == "true"'
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
    NODE_ENV: production
    PUBLIC_URL: https://k2804.gtilab.io/final-project-2
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public         
  artifacts:
    paths:
      - public